### ISSUE TITLE
Use in Laravel 5?

### ISSUE THREAD

**Issue by greggilbert** [BeatSwitch/lock-laravel#11]
I assume the answer is no, but is this package Laravel 5 ready yet? It installs fine, but on running `./artisan`:

```php
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in ~\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:168
Stack trace:
#0 ~\vendor\beatswitch\lock-laravel\src\LockServiceProvider.php(41): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 ~\vendor\beatswitch\lock-laravel\src\LockServiceProvider.php(41): BeatSwitch\Lock\Integrations\Laravel\LockServiceProvider->package('beatswitch/lock...', 'lock-laravel', 'E:\\Files\\Docume...')
#2 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(393): BeatSwitch\Lock\Integrations\Laravel\LockServiceProvider->register()
#3 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(514): Illuminate\Foundation\Application->register(Object(BeatSwitch\Lock\Integrations\Laravel\LockServiceProvider))
#4 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(496): Illuminate\Foundation\Application->registerDeferredProvider('BeatSwitch\\Lock...', 'lock')
#5 ~\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(470): Illuminate\Foundation\Application->loadDeferredProvider('lock')
#6 ~\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(183): Illuminate\Foundation\Application->loadDeferredProviders()
#7 ~\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#8 ~\artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}
```

Any ideas?

**Comment by driesvints** [comment]
Hey! No not yet. It's definitely on the todo list, I just haven't had the time yet to make it happen.

**Comment by Jamesking56** [comment]
Hey Laravel 5 has launched, I'd love to use this package with it if you're adding support for it?

**Comment by driesvints** [comment]
I definitely am, just haven't found the time yet sorry. Will try to knock it out later tonight or over the weekend.

**Comment by Jamesking56** [comment]
No problem, hit me up if you need any help :+1:

**Comment by iWader** [comment]
+1 any rough ETA on this?

Happy to submit a PR, although looks like #15 has done much of the changes.

**Comment by landjea** [comment]
+1 as well

**Comment by borantula** [comment]
+1

**Comment by driesvints** [comment]
Hey guys,

I'm really, really sorry it took this long but Laravel 5 support is finally merged in. All kudos go to @kirkbushell for the work in #17.

I've updated the docs with the new install instructions. If you notice any bug then please let me know!

Cheers
